[2024-06-13T05:31:44.441+0000] {processor.py:161} INFO - Started process (PID=42) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:31:44.443+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-13T05:31:44.447+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:31:44.446+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:31:46.160+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:31:46.151+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-13T05:31:46.163+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:31:46.213+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 1.785 seconds
[2024-06-13T05:32:16.812+0000] {processor.py:161} INFO - Started process (PID=109) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:32:16.814+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-13T05:32:16.817+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:32:16.816+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:32:17.328+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:32:17.324+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-13T05:32:17.331+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:32:17.344+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.540 seconds
[2024-06-13T05:32:47.620+0000] {processor.py:161} INFO - Started process (PID=169) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:32:47.621+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-13T05:32:47.622+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:32:47.622+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:32:47.975+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:32:47.972+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-13T05:32:47.977+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:32:47.990+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.375 seconds
[2024-06-13T05:33:18.366+0000] {processor.py:161} INFO - Started process (PID=229) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:33:18.367+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-13T05:33:18.369+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:33:18.369+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:33:18.740+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:33:18.736+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-13T05:33:18.742+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:33:18.761+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.400 seconds
[2024-06-13T05:33:49.037+0000] {processor.py:161} INFO - Started process (PID=289) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:33:49.038+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-13T05:33:49.039+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:33:49.039+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:33:49.373+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:33:49.370+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-13T05:33:49.374+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:33:49.386+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.353 seconds
[2024-06-13T05:34:19.435+0000] {processor.py:161} INFO - Started process (PID=349) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:34:19.437+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-13T05:34:19.439+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:34:19.439+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:34:20.054+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:34:20.045+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-13T05:34:20.057+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:34:20.088+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.660 seconds
[2024-06-13T05:34:50.737+0000] {processor.py:161} INFO - Started process (PID=411) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:34:50.738+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-13T05:34:50.740+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:34:50.740+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:34:51.081+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:34:51.078+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-13T05:34:51.082+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:34:51.092+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.359 seconds
[2024-06-13T05:35:21.301+0000] {processor.py:161} INFO - Started process (PID=474) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:35:21.302+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-13T05:35:21.304+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:35:21.304+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:35:21.748+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:35:21.742+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-13T05:35:21.750+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:35:21.766+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.469 seconds
[2024-06-13T05:36:37.095+0000] {processor.py:161} INFO - Started process (PID=42) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:36:37.097+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-13T05:36:37.099+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:36:37.099+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:36:38.660+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:36:38.652+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-13T05:36:38.663+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:36:38.688+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 1.602 seconds
[2024-06-13T05:37:09.290+0000] {processor.py:161} INFO - Started process (PID=109) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:37:09.291+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-13T05:37:09.292+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:37:09.292+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:37:09.623+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:37:09.620+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-13T05:37:09.624+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:37:09.636+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.350 seconds
[2024-06-13T05:37:39.950+0000] {processor.py:161} INFO - Started process (PID=169) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:37:39.951+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-13T05:37:39.952+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:37:39.952+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:37:40.293+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:37:40.290+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-13T05:37:40.294+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:37:40.303+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.357 seconds
[2024-06-13T05:38:10.565+0000] {processor.py:161} INFO - Started process (PID=229) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:38:10.566+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-13T05:38:10.567+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:38:10.567+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:38:10.917+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:38:10.894+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-13T05:38:10.921+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:38:10.933+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.372 seconds
[2024-06-13T05:38:41.011+0000] {processor.py:161} INFO - Started process (PID=292) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:38:41.012+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-13T05:38:41.014+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:38:41.013+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:38:41.319+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:38:41.317+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-13T05:38:41.320+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:38:41.330+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.322 seconds
[2024-06-13T05:39:11.429+0000] {processor.py:161} INFO - Started process (PID=355) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:39:11.430+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-13T05:39:11.432+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:39:11.431+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:39:11.790+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:39:11.786+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-13T05:39:11.792+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:39:11.804+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.379 seconds
[2024-06-13T05:39:41.914+0000] {processor.py:161} INFO - Started process (PID=419) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:39:41.915+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-13T05:39:41.916+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:39:41.916+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:39:42.330+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:39:42.325+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-13T05:39:42.331+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:39:42.343+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.435 seconds
[2024-06-13T05:42:25.928+0000] {processor.py:161} INFO - Started process (PID=41) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:42:25.931+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-13T05:42:25.933+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:42:25.933+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:42:27.567+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:42:27.559+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-13T05:42:27.570+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:42:27.599+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 1.678 seconds
[2024-06-13T05:42:57.740+0000] {processor.py:161} INFO - Started process (PID=108) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:42:57.741+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-13T05:42:57.742+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:42:57.742+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:42:58.094+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:42:58.085+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-13T05:42:58.096+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:42:58.106+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.370 seconds
[2024-06-13T05:43:28.244+0000] {processor.py:161} INFO - Started process (PID=170) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:43:28.245+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-13T05:43:28.247+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:43:28.247+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:43:28.653+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:43:28.594+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-13T05:43:28.662+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:43:28.676+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.436 seconds
[2024-06-13T05:43:58.848+0000] {processor.py:161} INFO - Started process (PID=230) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:43:58.850+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-13T05:43:58.851+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:43:58.851+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:43:59.156+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:43:59.153+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-13T05:43:59.158+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:43:59.167+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.323 seconds
[2024-06-13T05:44:29.280+0000] {processor.py:161} INFO - Started process (PID=294) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:44:29.281+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-13T05:44:29.283+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:44:29.283+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:44:29.580+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:44:29.577+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-13T05:44:29.581+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:44:29.593+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.317 seconds
[2024-06-13T05:44:59.866+0000] {processor.py:161} INFO - Started process (PID=346) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:44:59.867+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-13T05:44:59.869+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:44:59.869+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:45:00.200+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:45:00.194+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-13T05:45:00.202+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:45:00.214+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.352 seconds
[2024-06-13T05:45:31.089+0000] {processor.py:161} INFO - Started process (PID=407) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:45:31.090+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-13T05:45:31.092+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:45:31.091+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:45:31.481+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:45:31.467+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-13T05:45:31.482+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:45:31.492+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.407 seconds
[2024-06-13T05:46:01.940+0000] {processor.py:161} INFO - Started process (PID=467) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:46:01.942+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-13T05:46:01.943+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:46:01.943+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:46:02.285+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:46:02.273+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-13T05:46:02.289+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:46:02.300+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.364 seconds
[2024-06-13T05:46:32.534+0000] {processor.py:161} INFO - Started process (PID=530) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:46:32.535+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-13T05:46:32.536+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:46:32.536+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:46:32.865+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:46:32.862+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-13T05:46:32.868+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:46:32.879+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.349 seconds
[2024-06-13T05:47:02.968+0000] {processor.py:161} INFO - Started process (PID=587) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:47:02.969+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-13T05:47:02.970+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:47:02.970+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:47:03.275+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:47:03.272+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-13T05:47:03.276+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:47:03.286+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.322 seconds
[2024-06-13T05:47:33.683+0000] {processor.py:161} INFO - Started process (PID=647) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:47:33.684+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-13T05:47:33.685+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:47:33.685+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:47:33.998+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:47:33.995+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-13T05:47:33.998+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:47:34.012+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.333 seconds
[2024-06-13T05:49:57.990+0000] {processor.py:161} INFO - Started process (PID=42) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:49:57.992+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-13T05:49:57.994+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:49:57.994+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:49:59.669+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:49:59.659+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-13T05:49:59.673+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:49:59.712+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 1.728 seconds
[2024-06-13T05:50:29.877+0000] {processor.py:161} INFO - Started process (PID=109) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:50:29.878+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-13T05:50:29.880+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:50:29.879+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:50:30.229+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:50:30.222+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-13T05:50:30.230+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:50:30.244+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.371 seconds
[2024-06-13T05:51:00.303+0000] {processor.py:161} INFO - Started process (PID=171) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:51:00.304+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-13T05:51:00.305+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:51:00.305+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:51:00.640+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:51:00.635+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-13T05:51:00.642+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:51:00.653+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.354 seconds
[2024-06-13T05:51:30.719+0000] {processor.py:161} INFO - Started process (PID=233) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:51:30.720+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-13T05:51:30.722+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:51:30.722+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:51:31.080+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:51:31.072+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-13T05:51:31.081+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:51:31.092+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.378 seconds
[2024-06-13T05:52:01.273+0000] {processor.py:161} INFO - Started process (PID=297) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:52:01.274+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-13T05:52:01.276+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:52:01.276+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:52:01.720+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:52:01.713+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-13T05:52:01.722+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:52:01.739+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.471 seconds
[2024-06-13T05:52:32.632+0000] {processor.py:161} INFO - Started process (PID=360) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:52:32.633+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-13T05:52:32.635+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:52:32.635+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:52:32.997+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:52:32.992+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-13T05:52:32.998+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:52:33.009+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.382 seconds
[2024-06-13T05:53:03.054+0000] {processor.py:161} INFO - Started process (PID=423) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:53:03.055+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-13T05:53:03.057+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:53:03.057+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:53:03.431+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:53:03.428+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-13T05:53:03.433+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:53:03.443+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.393 seconds
[2024-06-13T05:53:33.560+0000] {processor.py:161} INFO - Started process (PID=488) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:53:33.561+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-13T05:53:33.563+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:53:33.562+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:53:33.973+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:53:33.968+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-13T05:53:33.975+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:53:33.997+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.442 seconds
[2024-06-13T05:54:04.863+0000] {processor.py:161} INFO - Started process (PID=551) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:54:04.864+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-13T05:54:04.866+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:54:04.865+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:54:05.197+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:54:05.193+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-13T05:54:05.198+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:54:05.212+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.354 seconds
[2024-06-13T05:54:35.361+0000] {processor.py:161} INFO - Started process (PID=612) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:54:35.361+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-13T05:54:35.363+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:54:35.363+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:54:35.710+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:54:35.707+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-13T05:54:35.711+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:54:35.721+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.365 seconds
[2024-06-13T05:55:05.807+0000] {processor.py:161} INFO - Started process (PID=675) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:55:05.807+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-13T05:55:05.809+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:55:05.809+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:55:06.128+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:55:06.119+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-13T05:55:06.129+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:55:06.142+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.340 seconds
[2024-06-13T05:55:36.238+0000] {processor.py:161} INFO - Started process (PID=738) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:55:36.239+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-13T05:55:36.241+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:55:36.241+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:55:36.618+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:55:36.611+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-13T05:55:36.620+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:55:36.653+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.419 seconds
[2024-06-13T05:56:07.328+0000] {processor.py:161} INFO - Started process (PID=798) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:56:07.329+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-13T05:56:07.331+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:56:07.331+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:56:07.646+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:56:07.641+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-13T05:56:07.647+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:56:07.657+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.333 seconds
[2024-06-13T05:56:37.919+0000] {processor.py:161} INFO - Started process (PID=858) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:56:37.921+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-13T05:56:37.926+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:56:37.926+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:56:38.292+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:56:38.247+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-13T05:56:38.311+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:56:38.336+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.421 seconds
[2024-06-13T05:57:08.961+0000] {processor.py:161} INFO - Started process (PID=918) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:57:08.961+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-13T05:57:08.963+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:57:08.963+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:57:09.288+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:57:09.285+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-13T05:57:09.289+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:57:09.299+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.342 seconds
[2024-06-13T05:57:39.944+0000] {processor.py:161} INFO - Started process (PID=984) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:57:39.945+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-13T05:57:39.947+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:57:39.947+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:57:40.286+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:57:40.281+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-13T05:57:40.287+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:57:40.300+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.360 seconds
[2024-06-13T05:58:10.391+0000] {processor.py:161} INFO - Started process (PID=1047) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:58:10.392+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-13T05:58:10.394+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:58:10.394+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:58:10.917+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:58:10.911+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-13T05:58:10.919+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:58:10.937+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.552 seconds
[2024-06-13T05:58:41.849+0000] {processor.py:161} INFO - Started process (PID=1110) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:58:41.850+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-13T05:58:41.852+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:58:41.851+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:58:42.203+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:58:42.185+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-13T05:58:42.205+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:58:42.218+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.374 seconds
[2024-06-13T05:59:12.728+0000] {processor.py:161} INFO - Started process (PID=1170) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:59:12.729+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-13T05:59:12.730+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:59:12.730+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:59:13.052+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:59:13.049+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-13T05:59:13.053+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:59:13.063+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.340 seconds
[2024-06-13T05:59:43.200+0000] {processor.py:161} INFO - Started process (PID=1233) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:59:43.201+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-13T05:59:43.203+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:59:43.202+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:59:43.542+0000] {logging_mixin.py:188} INFO - [2024-06-13T05:59:43.539+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-13T05:59:43.543+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T05:59:43.556+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.359 seconds
[2024-06-13T06:00:14.239+0000] {processor.py:161} INFO - Started process (PID=1293) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:00:14.240+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-13T06:00:14.242+0000] {logging_mixin.py:188} INFO - [2024-06-13T06:00:14.241+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:00:14.560+0000] {logging_mixin.py:188} INFO - [2024-06-13T06:00:14.555+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-13T06:00:14.562+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:00:14.578+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.343 seconds
[2024-06-13T06:00:44.646+0000] {processor.py:161} INFO - Started process (PID=1354) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:00:44.648+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-13T06:00:44.650+0000] {logging_mixin.py:188} INFO - [2024-06-13T06:00:44.650+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:00:45.154+0000] {logging_mixin.py:188} INFO - [2024-06-13T06:00:45.127+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-13T06:00:45.156+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:00:45.171+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.531 seconds
[2024-06-13T06:01:15.782+0000] {processor.py:161} INFO - Started process (PID=1414) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:01:15.783+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-13T06:01:15.785+0000] {logging_mixin.py:188} INFO - [2024-06-13T06:01:15.784+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:01:16.188+0000] {logging_mixin.py:188} INFO - [2024-06-13T06:01:16.174+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-13T06:01:16.204+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:01:16.231+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.453 seconds
[2024-06-13T06:01:47.190+0000] {processor.py:161} INFO - Started process (PID=1479) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:01:47.191+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-13T06:01:47.193+0000] {logging_mixin.py:188} INFO - [2024-06-13T06:01:47.193+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:01:47.517+0000] {logging_mixin.py:188} INFO - [2024-06-13T06:01:47.514+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-13T06:01:47.518+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:01:47.529+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.342 seconds
[2024-06-13T06:02:18.372+0000] {processor.py:161} INFO - Started process (PID=1539) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:02:18.377+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-13T06:02:18.379+0000] {logging_mixin.py:188} INFO - [2024-06-13T06:02:18.378+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:02:18.677+0000] {logging_mixin.py:188} INFO - [2024-06-13T06:02:18.674+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-13T06:02:18.678+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:02:18.690+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.322 seconds
[2024-06-13T06:02:49.382+0000] {processor.py:161} INFO - Started process (PID=1599) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:02:49.383+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-13T06:02:49.384+0000] {logging_mixin.py:188} INFO - [2024-06-13T06:02:49.384+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:02:49.696+0000] {logging_mixin.py:188} INFO - [2024-06-13T06:02:49.693+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-13T06:02:49.697+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:02:49.707+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.329 seconds
[2024-06-13T06:03:20.007+0000] {processor.py:161} INFO - Started process (PID=1659) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:03:20.008+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-13T06:03:20.010+0000] {logging_mixin.py:188} INFO - [2024-06-13T06:03:20.009+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:03:20.309+0000] {logging_mixin.py:188} INFO - [2024-06-13T06:03:20.306+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-13T06:03:20.310+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:03:20.323+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.320 seconds
[2024-06-13T06:03:50.653+0000] {processor.py:161} INFO - Started process (PID=1719) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:03:50.654+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-13T06:03:50.656+0000] {logging_mixin.py:188} INFO - [2024-06-13T06:03:50.656+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:03:50.944+0000] {logging_mixin.py:188} INFO - [2024-06-13T06:03:50.941+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-13T06:03:50.945+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:03:50.957+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.308 seconds
[2024-06-13T06:04:21.275+0000] {processor.py:161} INFO - Started process (PID=1779) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:04:21.276+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-13T06:04:21.278+0000] {logging_mixin.py:188} INFO - [2024-06-13T06:04:21.277+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:04:21.625+0000] {logging_mixin.py:188} INFO - [2024-06-13T06:04:21.621+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-13T06:04:21.626+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:04:21.640+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.370 seconds
[2024-06-13T06:04:52.271+0000] {processor.py:161} INFO - Started process (PID=1839) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:04:52.277+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-13T06:04:52.285+0000] {logging_mixin.py:188} INFO - [2024-06-13T06:04:52.285+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:04:52.856+0000] {logging_mixin.py:188} INFO - [2024-06-13T06:04:52.852+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-13T06:04:52.858+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:04:52.871+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.605 seconds
[2024-06-13T06:05:23.660+0000] {processor.py:161} INFO - Started process (PID=1899) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:05:23.661+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-13T06:05:23.663+0000] {logging_mixin.py:188} INFO - [2024-06-13T06:05:23.662+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:05:23.986+0000] {logging_mixin.py:188} INFO - [2024-06-13T06:05:23.983+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-13T06:05:23.987+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:05:23.999+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.343 seconds
[2024-06-13T06:05:54.305+0000] {processor.py:161} INFO - Started process (PID=1959) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:05:54.306+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-13T06:05:54.308+0000] {logging_mixin.py:188} INFO - [2024-06-13T06:05:54.307+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:05:54.614+0000] {logging_mixin.py:188} INFO - [2024-06-13T06:05:54.611+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-13T06:05:54.615+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:05:54.628+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.327 seconds
[2024-06-13T06:06:25.152+0000] {processor.py:161} INFO - Started process (PID=2019) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:06:25.154+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-13T06:06:25.160+0000] {logging_mixin.py:188} INFO - [2024-06-13T06:06:25.159+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:06:26.088+0000] {logging_mixin.py:188} INFO - [2024-06-13T06:06:26.082+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-13T06:06:26.091+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:06:26.120+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.984 seconds
[2024-06-13T06:06:56.755+0000] {processor.py:161} INFO - Started process (PID=2079) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:06:56.757+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-13T06:06:56.760+0000] {logging_mixin.py:188} INFO - [2024-06-13T06:06:56.759+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:06:57.479+0000] {logging_mixin.py:188} INFO - [2024-06-13T06:06:57.472+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-13T06:06:57.482+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:06:57.507+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.762 seconds
[2024-06-13T06:08:43.884+0000] {processor.py:161} INFO - Started process (PID=48) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:08:43.893+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-13T06:08:43.911+0000] {logging_mixin.py:188} INFO - [2024-06-13T06:08:43.910+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:08:48.545+0000] {logging_mixin.py:188} INFO - [2024-06-13T06:08:48.509+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-13T06:08:48.552+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:08:48.831+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 4.992 seconds
[2024-06-13T06:25:23.472+0000] {processor.py:161} INFO - Started process (PID=42) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:25:23.474+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-13T06:25:23.476+0000] {logging_mixin.py:188} INFO - [2024-06-13T06:25:23.475+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:25:25.741+0000] {logging_mixin.py:188} INFO - [2024-06-13T06:25:25.734+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 28, in <module>
    task_train_test_split = PythonOperator(
                            ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 222, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2024-06-13T06:25:25.743+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:25:25.765+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 2.297 seconds
[2024-06-13T06:25:55.993+0000] {processor.py:161} INFO - Started process (PID=136) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:25:55.994+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-13T06:25:55.996+0000] {logging_mixin.py:188} INFO - [2024-06-13T06:25:55.996+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:25:57.150+0000] {logging_mixin.py:188} INFO - [2024-06-13T06:25:57.144+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 28, in <module>
    task_train_test_split = PythonOperator(
                            ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 222, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2024-06-13T06:25:57.151+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:25:57.174+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 1.188 seconds
[2024-06-13T06:26:27.547+0000] {processor.py:161} INFO - Started process (PID=216) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:26:27.548+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-13T06:26:27.549+0000] {logging_mixin.py:188} INFO - [2024-06-13T06:26:27.549+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:26:28.300+0000] {logging_mixin.py:188} INFO - [2024-06-13T06:26:28.293+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 28, in <module>
    task_train_test_split = PythonOperator(
                            ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 222, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2024-06-13T06:26:28.301+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:26:28.319+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.776 seconds
[2024-06-13T06:26:58.653+0000] {processor.py:161} INFO - Started process (PID=303) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:26:58.654+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-13T06:26:58.656+0000] {logging_mixin.py:188} INFO - [2024-06-13T06:26:58.655+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:26:59.502+0000] {logging_mixin.py:188} INFO - [2024-06-13T06:26:59.495+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 28, in <module>
    task_train_test_split = PythonOperator(
                            ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 222, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2024-06-13T06:26:59.503+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:26:59.518+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.869 seconds
[2024-06-13T06:27:30.013+0000] {processor.py:161} INFO - Started process (PID=386) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:27:30.014+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-13T06:27:30.015+0000] {logging_mixin.py:188} INFO - [2024-06-13T06:27:30.015+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:27:30.628+0000] {logging_mixin.py:188} INFO - [2024-06-13T06:27:30.624+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 28, in <module>
    task_train_test_split = PythonOperator(
                            ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 222, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2024-06-13T06:27:30.628+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:27:30.639+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.629 seconds
[2024-06-13T06:28:00.855+0000] {processor.py:161} INFO - Started process (PID=470) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:28:00.856+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-13T06:28:00.858+0000] {logging_mixin.py:188} INFO - [2024-06-13T06:28:00.857+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:28:01.502+0000] {logging_mixin.py:188} INFO - [2024-06-13T06:28:01.498+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 28, in <module>
    task_train_test_split = PythonOperator(
                            ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 222, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2024-06-13T06:28:01.503+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:28:01.521+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.670 seconds
[2024-06-13T06:28:10.350+0000] {processor.py:161} INFO - Started process (PID=522) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:28:10.352+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-13T06:28:10.353+0000] {logging_mixin.py:188} INFO - [2024-06-13T06:28:10.353+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:28:11.016+0000] {logging_mixin.py:188} INFO - [2024-06-13T06:28:11.011+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 28, in <module>
    task_train_test_split = PythonOperator(
                            ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 222, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2024-06-13T06:28:11.017+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:28:11.027+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.680 seconds
[2024-06-13T06:28:15.739+0000] {processor.py:161} INFO - Started process (PID=544) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:28:15.739+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-13T06:28:15.741+0000] {logging_mixin.py:188} INFO - [2024-06-13T06:28:15.741+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:28:16.369+0000] {logging_mixin.py:188} INFO - [2024-06-13T06:28:16.364+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 28, in <module>
    task_train_test_split = PythonOperator(
                            ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 222, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2024-06-13T06:28:16.370+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:28:16.383+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.648 seconds
[2024-06-13T06:29:39.905+0000] {processor.py:161} INFO - Started process (PID=42) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:29:39.906+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-13T06:29:39.909+0000] {logging_mixin.py:188} INFO - [2024-06-13T06:29:39.909+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:29:42.415+0000] {logging_mixin.py:188} INFO - [2024-06-13T06:29:42.404+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 28, in <module>
    task_train_test_split = PythonOperator(
                            ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 222, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2024-06-13T06:29:42.416+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:29:42.442+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 2.546 seconds
[2024-06-13T06:30:12.611+0000] {processor.py:161} INFO - Started process (PID=136) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:30:12.612+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-13T06:30:12.613+0000] {logging_mixin.py:188} INFO - [2024-06-13T06:30:12.613+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:30:13.312+0000] {logging_mixin.py:188} INFO - [2024-06-13T06:30:13.306+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 28, in <module>
    task_train_test_split = PythonOperator(
                            ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 222, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2024-06-13T06:30:13.313+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:30:13.325+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.718 seconds
[2024-06-13T06:30:43.716+0000] {processor.py:161} INFO - Started process (PID=216) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:30:43.718+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-13T06:30:43.720+0000] {logging_mixin.py:188} INFO - [2024-06-13T06:30:43.719+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:30:44.841+0000] {logging_mixin.py:188} INFO - [2024-06-13T06:30:44.831+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 28, in <module>
    task_train_test_split = PythonOperator(
                            ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 222, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2024-06-13T06:30:44.842+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:30:44.858+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 1.147 seconds
[2024-06-13T06:31:15.130+0000] {processor.py:161} INFO - Started process (PID=303) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:31:15.130+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-13T06:31:15.132+0000] {logging_mixin.py:188} INFO - [2024-06-13T06:31:15.132+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:31:15.758+0000] {logging_mixin.py:188} INFO - [2024-06-13T06:31:15.753+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 28, in <module>
    task_train_test_split = PythonOperator(
                            ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 222, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2024-06-13T06:31:15.759+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:31:15.775+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.650 seconds
[2024-06-13T06:31:38.119+0000] {processor.py:161} INFO - Started process (PID=362) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:31:38.120+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-13T06:31:38.122+0000] {logging_mixin.py:188} INFO - [2024-06-13T06:31:38.121+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:31:38.756+0000] {processor.py:840} INFO - DAG(s) 'ml_pipelines' retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:31:38.814+0000] {logging_mixin.py:188} INFO - [2024-06-13T06:31:38.813+0000] {override.py:1829} INFO - Created Permission View: can read on DAG:ml_pipelines
[2024-06-13T06:31:38.820+0000] {logging_mixin.py:188} INFO - [2024-06-13T06:31:38.820+0000] {override.py:1829} INFO - Created Permission View: can delete on DAG:ml_pipelines
[2024-06-13T06:31:38.824+0000] {logging_mixin.py:188} INFO - [2024-06-13T06:31:38.824+0000] {override.py:1829} INFO - Created Permission View: can edit on DAG:ml_pipelines
[2024-06-13T06:31:38.825+0000] {logging_mixin.py:188} INFO - [2024-06-13T06:31:38.825+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-13T06:31:38.831+0000] {logging_mixin.py:188} INFO - [2024-06-13T06:31:38.831+0000] {dag.py:3118} INFO - Creating ORM DAG for ml_pipelines
[2024-06-13T06:31:38.837+0000] {logging_mixin.py:188} INFO - [2024-06-13T06:31:38.837+0000] {dag.py:3954} INFO - Setting next_dagrun for ml_pipelines to 2024-06-18 00:00:00+00:00, run_after=2024-06-19 00:00:00+00:00
[2024-06-13T06:31:38.849+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.735 seconds
[2024-06-13T06:32:53.365+0000] {processor.py:161} INFO - Started process (PID=42) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:32:53.367+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-13T06:32:53.370+0000] {logging_mixin.py:188} INFO - [2024-06-13T06:32:53.369+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:32:55.979+0000] {processor.py:840} INFO - DAG(s) 'ml_pipelines' retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:32:56.283+0000] {logging_mixin.py:188} INFO - [2024-06-13T06:32:56.282+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-13T06:32:56.315+0000] {logging_mixin.py:188} INFO - [2024-06-13T06:32:56.315+0000] {dag.py:3954} INFO - Setting next_dagrun for ml_pipelines to 2024-06-18 00:00:00+00:00, run_after=2024-06-19 00:00:00+00:00
[2024-06-13T06:32:56.351+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 2.996 seconds
[2024-06-13T06:33:26.489+0000] {processor.py:161} INFO - Started process (PID=136) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:33:26.490+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-13T06:33:26.492+0000] {logging_mixin.py:188} INFO - [2024-06-13T06:33:26.492+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:33:27.386+0000] {processor.py:840} INFO - DAG(s) 'ml_pipelines' retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-13T06:33:27.401+0000] {logging_mixin.py:188} INFO - [2024-06-13T06:33:27.401+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-13T06:33:27.422+0000] {logging_mixin.py:188} INFO - [2024-06-13T06:33:27.422+0000] {dag.py:3954} INFO - Setting next_dagrun for ml_pipelines to 2024-06-18 00:00:00+00:00, run_after=2024-06-19 00:00:00+00:00
[2024-06-13T06:33:27.442+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.958 seconds
